### PR TITLE
Add Apache2 License.

### PR DESCRIPTION
**Pull request by chrismattmann**
Add an ALv2 license for the Python Tika bindings.

### CODE REVIEW

**Comment by Bengt** [comment]
Hello, thanks for this pull request.

Is it by intention that you issued the pull request against my fork and not the original repo ([aptivate/python-tika](https://github.com/aptivate/python-tika)) or the one I forked ([cruns/python-tika-with-deps](https://github.com/cruns/python-tika-with-deps))?

I am not the original author of the code, so I can not add a license to it.

**Comment by chrismattmann** [comment]
Hi Bengt, do you know how I can issue the request against aptivate? I tried doing it and somehow I think b/c I had checked out (forked) your code it put it against your distro. BTW, since there is no license file upstream you _can_ license your derivative work (even if there was a license file upstream you could still license your derivative work).

Let me know what you think and thanks!

**Comment by Bengt** [comment]
You can Issue a Pull Request against aptivate there: https://github.com/aptivate/python-tika/compare/

I do not know copyright too well. Under which terms do think this is a derivative work and such can be licensed by its author if the source is not licensed?

Given that I could license this repo, why are you suggesting this license? Has anyone in any of the forks ever expressed himself in favor of the APL?

**Comment by chrismattmann** [comment]
Hi Bengt, thanks, I tried that but Github became confused since I already have another Fork of the same name. BTW, yes this would seem like a derivative work to me, so you are free to license (in the absence of one upstream). I'm suggesting the Apache License version 2 b/c I think it's the most permissive, and best license IMO out there. I've participated in the Apache Software Foundation since 2005 and favor academic/permissive licenses, and between ALv2, BSD, and MIT, ALv2 ("Apache Software License, version 2") has patent termination which protects downstream users and for those reasons, I think it's the best license.

**Comment by chrismattmann** [comment]
I'm happy to close this. [Tika Python](http://github.com/chrismattmann/tika-python) is now pretty fully featured and awesome. And ALv2 licensed :) :+1:

**Pull request closed without merging**
